language: node_js
node_js:
  - "0.12"
env:
  global:
    secure: INekObfHOhYCLMpwWQC77KlNZMvXbW8CJ4KicfL2fsxC/IpYrA5+lFS1LeaC6eDDf47x2Wqo4op9SeUspOUrGJfMVo4Lv/0HyRgZYkRbkvtDfz34x4S+X6HrE6mmsT5I1XjbqPgf3HBEmLDYOVKKh+jsAq1wYc364tbXhqtnQbh3oZSnAXyq6EvfKZHuRO0U0vs6g8q4clnqbw47jP6yN6xLuRb9Hb3qnLwk/8Z45lcwB4jF5qJVDn7Q4KFw0b6UbRcpF8WHWH2po17dX7IJ9ksNnYN1feNkCIXe64QqAuEZmI1xMVh2EKW2Cmm6DV9ceq4iUUIaHpIx8jtEP057GSq83zc3c+e/hSRFD0R2KHd+3uKapPxWd9fFh5V3xnRAt9+AAFH8RXTpmr3Y8IGGkzOSdtaOHTNKpPrEE7HAEQdr8qeXz5D3yfhSf03I9tQctNK9tGWaWMf9Cv+G7SdbuD6I+q3kAiIFFZqfZP32gDWk6MEbn71s33NBW3apP33V5BSRtRFEzOfyJ+SUjP0FiIgE1pdwHTCHI3oydDMb6ToG2dwV8pRdTfvEG1gSFuBxOZIqNBmP/Gleed6tZOwuGVBdgS48HslErOMu9LN0ofWu4p4zrAEsG3aiqJQSC7ovVwpfcRVDdtHxO/8wj+/q+Y1AecAfpHAteETqNFFrk00=
before_install:
  - openssl aes-256-cbc -K $encrypted_283c29934c17_key -iv $encrypted_283c29934c17_iv -in deploy/id_rsa.enc -out deploy/id_rsa -d
  - chmod 600 deploy/id_rsa
  - eval "$(ssh-agent)"
  - ssh-add deploy/id_rsa
  - git config --global user.name "$GIT_NAME"
  - git config --global  user.email "$GIT_EMAIL"

before_script:
  - travis_retry npm install --no-spin --quiet -g gulp http-server
  - travis_retry npm install --no-spin
  - travis_retry gulp bower:install
  - gulp build
  - http-server ./app/build/ -p 8001 2>&1 >/dev/null & #start webserver
  - sleep 5 #give server some time to boot

script:
  - ./node_modules/.bin/cucumber.js

after_success:
  - if [[ ( "$TRAVIS_BRANCH" == "master" ) && ( "$TRAVIS_PULL_REQUEST" == "false" ) ]]; then sudo chmod 777 ./deploy/deploy.sh && ./deploy/deploy.sh; fi